name: network-manager-tui
version: 1.0.0.0
github: "andys8/network-manager-tui"
license: BSD3
author: "andys8"
maintainer: "andys8@users.noreply.github.com"
copyright: "andys8"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: network-manager tui
category: Tui

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/andys8/network-manager-tui#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - microlens
  - process
  - split
  - vector
  - vty

internal-libraries:
  network-manager-tui-lib:
    source-dirs: src
    ghc-options:
      - -Wall

flags:
  static:
    manual: true
    default: false

executables:
  nmt:
    main: Main.hs
    source-dirs: app
    generated-other-modules:
      - Paths_network_manager_tui
    when:
      - condition: flag(static)
        then:
          cc-options: -static
          ld-options: -static -pthread
          ghc-options:
            - -static
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        else:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
    dependencies:
      - network-manager-tui-lib

tests:
  nmt-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - network-manager-tui-lib
      - hspec
